[project]
name = "finperf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexandre Gallego Mato", email = "alexandre.gallego.mato@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
finperf = "finperf:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
